### ISSUE TITLE
failing cases

### ISSUE THREAD

**Issue by Fil** [substack/pclip#4]
Hello

in  https://observablehq.com/@fil/hello-pclip-hmmmm I'm trying to apply pclip to my usual test case. The xy version sort of works but often fails in the top of the map; the geo version is super slow and doesn't result in usable shapes (maybe because of winding order?).

**Comment by substack** [comment]
pclip doesn't deal with winding order at all. It doesn't surprise me that the cartesian version breaks at the poles, that was my initial motivation for this module. Can you try putting the output with `pclip/geo` through https://www.npmjs.com/package/geojson-rewind ?

**Comment by Fil** [comment]
Thanks! My main error was that I forgot to add the _duplicate: true_ parameter. I've fixed the notebook, added a custom rewinding function, and now things are working (the geo version is very slow, but that's a separate matter).
